macOS_task:
  osx_instance:
    image: mojave-xcode-10.2
  prepare_script: brew install cmake && brew install pkg-config && mkdir build
  configure_script: cd ./build && cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script: cmake --build ./build --config MinSizeRel
  test_script: ./build/bin/relive-test

Ubuntu_task:
  container:
    image: ubuntu:latest
  prepare_script: apt update && apt install -y build-essential && apt install -y cmake && apt install -y git && apt install -y pkg-config && mkdir build 
  configure_script: cd ./build && cmake  -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script: cmake --build ./build --config MinSizeRel
  test_script: ./build/bin/relive-test

FreeBSD_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  prepare_script: pkg install -y cmake && pkg install -y git && pkg install -y pkgconf && mkdir build
  configure_script: cd ./build && cmake  -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script: cmake --build ./build --config MinSizeRel
  test_script: ./build/bin/relive-test

