macOS_task:
  osx_instance:
    image: mojave-xcode-10.2
  prepare_script:
    - brew install cmake
    - brew install pkg-config
    - brew install sqlite
    - mkdir build
  configure_script:
    - cd ./build
    - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script:
    - cd ./build
    - cmake --build . --config MinSizeRel
    - cpack -G DragNDrop
  test_script:
    - ./build/bin/relive-test
  pkg_artifacts:
    path: "./build/*.pkg"

Ubuntu_task:
  container:
    image: ubuntu:latest
    memory: 12
  prepare_script:
    - apt update
    - apt install -y build-essential
    - apt install -y clang-6.0
    - apt install -y cmake
    - apt install -y git
    - apt install -y pkg-config
    - apt install -y libasound2-dev
    - apt install -y libncursesw5-dev
    - mkdir build 
  configure_script:
    - cd ./build
    - cmake  -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script:
    - cd ./build
    - cmake --build . --config MinSizeRel
    - cpack -G DEB
  test_script:
    - ./build/bin/relive-test
  deb_artifacts:
    path: "./build/*.deb"

FreeBSD_task:
  only_if: $CIRRUS_BRANCH =~ 'do-not-build' # FreeBSD builds are disabled untill I have a vm to debug
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  prepare_script:
    - pkg install -y cmake
    - pkg install -y git
    - pkg install -y pkgconf
    - pkg install -y devel/ncurses
    - mkdir build
  configure_script:
    - cd ./build
    - cmake  -DCMAKE_BUILD_TYPE=MinSizeRel ..
  build_script:
    - cmake --build ./build --config MinSizeRel
  test_script:
    - ./build/bin/relive-test

