
if(APPLE)
    set(CPACK_COMPONENTS_ALL application)
    set(CPACK_productbuild_COMPONENT_INSTALL ON)
    if(CPACK_GENERATOR MATCHES "productbuild")
        set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
    elseif()
        set(CPACK_PACKAGING_INSTALL_PREFIX "/")
    else()
elseif(UNIX)
    find_program(DPKG_CMD dpkg)
    if(DPKG_CMD)
        set(CPACK_GENERATOR "DEB")
        set(CPACK_BINARY_DEB "ON")
        set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    else()
        find_program(RPMBUILD_CMD rpmbuild)
        if(RPMBUILD_CMD)
            set(CPACK_GENERATOR "RPM")
        else()
            set(CPACK_GENERATOR "TGZ")
        endif()
    endif()
elseif(WIN32)
    set(CPACK_GENERATOR "NSIS")
endif()

message(STATUS "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "")
set(CPACK_SYSTEM_NAME "${HOST_OS}")
set(CPACK_PACKAGE_NAME "relivecui")
set(CPACK_PACKAGE_FILE_NAME "foo-${CPACK_PACKAGE_NAME}-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-${CPACK_SYSTEM_NAME}")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VENDOR "gulrak.relive")
set(CPACK_PACKAGE_CONTACT "s.schuemann@pobox.com")
set(CPACK_PACKAGE_DESCRIPTION "A curses based stream replayer for reLive archives (http://relive.nu)")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://relive.gulrak.net")

